### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by zba** [remiheens/mattermost-docker-arm#25]
I made config like this:

```
version: "3"

services:
  db:
    image: rheens/mattermost-db:v9.0.1
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=mattermost
  app:
    image: rheens/mattermost-app:v9.0.1
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=admin
      - MM_PASSWORD=admin
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=postgres://pguser:pgpass@db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://localhost/
```

and got

```
mattermost-docker-arm-app-1  | No configuration file /mattermost/config/config.json
mattermost-docker-arm-app-1  | Creating a new one
mattermost-docker-arm-app-1  | cp: can't stat '/config.json.save': No such file or directory
mattermost-docker-arm-app-1  | /entrypoint.sh: line 44: can't create /mattermost/config/config.json.tmp: Permission denied
mattermost-docker-arm-app-1  | /entrypoint.sh: line 45: can't create /mattermost/config/config.json.tmp: Permission denied
mattermost-docker-arm-app-1  | /entrypoint.sh: line 46: can't create /mattermost/config/config.json.tmp: Permission denied
mattermost-docker-arm-app-1  | /entrypoint.sh: line 47: can't create /mattermost/config/config.json.tmp: Permission denied
mattermost-docker-arm-app-1  | /entrypoint.sh: line 48: can't create /mattermost/config/config.json.tmp: Permission denied
```

I checked, there some suid bits and other strange solutions, not sure how to fix. 

any ideas ?
